spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
jwt.secret=test-secret-key-for-integration-tests-only-not-secure-do-not-use-in-prod
copernicus.username=test-mock
copernicus.password=test-mock
nasa.earthdata.token=test-mock
